# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: dabby04@student.ubc.ca
author_name: Oluwadabira
has_binder: true
has_settings: false
kind: server
labextension_name: bugspyter
project_short_description: A JupyterLab extension that uses AI agents to detect buggy
    and vulnerable code.
python_name: bugspyter
repository: https://github.com/github_username/bugspyter
test: true

